---

- name: Create namespace for IP failover objects
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    api_version: v1
    kind: Namespace
    name: ipfailover
  vars:
    cluster: "{{ groups['rke_' + inventory_hostname] }}"

- name: Create IPv4 failover DaemonSet
  k8s:
    kubeconfig: "{{ rke_cluster_kube_config }}"
    state: present
    definition: "{{ lookup('template', 'ds_faiilover.yml.j2') }}"
  with_items:
    - "{{ rancher_failover_ip }}"
  vars:
    cluster: "{{ groups['rke_' + inventory_hostname] }}"
    unicast_peers: "{% for node in cluster %}''{{ hostvars[node]['ansible_eth0']['ipv4']['address'] }}'',{% endfor %}"
    keepalived_image_version: "{{ keepalived_image_version }}"

