---

- name: Create or get Cluster
  delegate_to: localhost
  import_tasks: cluster.yml

- name: Nodes
  delegate_to: localhost
  import_tasks: nodes.yml

- name: Configure keepalived
  delegate_to: localhost
  include_role:
  name: keepalived
